name: cron
on: 
  schedule:
    - cron: '0 21 * * *'
  push:
    branches: 
      - master
  workflow_dispatch:
jobs:
  download:
    runs-on: Ubuntu-20.04

    steps:
    - name: Download
      run: |
        HEAD = "Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
        Accept-Encoding:gzip, deflate, sdch
        Accept-Language:zh-CN,zh;q=0.8,en;q=0.6
        Authorization:Digest username="admin", realm="UTT", nonce="4bea64239fe34c7d68ececbe053f9eb4", uri="/WANConfig.asp", algorithm=MD5, response="f2b1aed87b72e0e27f2a12647b0d150d", opaque="5ccc069c403ebaf9f0171e9517f40e41", qop=auth, nc=000002c5, cnonce="7f2abdd864b961a5"
        Cache-Control:max-age=0
        Connection:keep-alive
        Cookie:COOKIE=c0a8016400000c00; language=zhcn; utt_bw_rdevType=
        Host:192.168.1.1
        Upgrade-Insecure-Requests:1
        User-Agent:Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36"
        mkdir ./bing
        cd ./bing
        curl  -H $HEAD https://api.mhuig.top/bing?day=0 -o bing.jpg
        curl  -H $HEAD https://api.mhuig.top/bing?day=1 -o 1.jpg
        curl  -H $HEAD https://api.mhuig.top/bing?day=2 -o 2.jpg
        curl  -H $HEAD https://api.mhuig.top/bing?day=3 -o 3.jpg
        curl  -H $HEAD https://api.mhuig.top/bing?day=4 -o 4.jpg
        curl  -H $HEAD https://api.mhuig.top/bing?day=5 -o 5.jpg
        curl  -H $HEAD https://api.mhuig.top/bing?day=6 -o 6.jpg
        curl  -H $HEAD https://api.mhuig.top/bing?day=7 -o 7.jpg
        curl  -H $HEAD https://api.mhuig.top/bingcopyright/w?day=0 -o bing.js
        curl  -H $HEAD https://api.mhuig.top/bingcopyright/w?day=1 -o 1.js
        curl  -H $HEAD https://api.mhuig.top/bingcopyright/w?day=2 -o 2.js
        curl  -H $HEAD https://api.mhuig.top/bingcopyright/w?day=3 -o 3.js
        curl  -H $HEAD https://api.mhuig.top/bingcopyright/w?day=4 -o 4.js
        curl  -H $HEAD https://api.mhuig.top/bingcopyright/w?day=5 -o 5.js
        curl  -H $HEAD https://api.mhuig.top/bingcopyright/w?day=6 -o 6.js
        curl  -H $HEAD https://api.mhuig.top/bingcopyright/w?day=7 -o 7.js
        curl  -H $HEAD https://api.mhuig.top/binginfo?day=0 -o bing.json
        curl  -H $HEAD https://api.mhuig.top/binginfo?day=1 -o 1.json
        curl  -H $HEAD https://api.mhuig.top/binginfo?day=2 -o 2.json
        curl  -H $HEAD https://api.mhuig.top/binginfo?day=3 -o 3.json
        curl  -H $HEAD https://api.mhuig.top/binginfo?day=4 -o 4.json
        curl  -H $HEAD https://api.mhuig.top/binginfo?day=5 -o 5.json
        curl  -H $HEAD https://api.mhuig.top/binginfo?day=6 -o 6.json
        curl  -H $HEAD https://api.mhuig.top/binginfo?day=7 -o 7.json
        cd ..
        mkdir ./soul
        cd ./soul
        curl  -H $HEAD https://api.mhuig.top/soul -o soul.json
        curl  -H $HEAD https://api.mhuig.top/soul/w -o soul.js
        cd ..
        mkdir ./hitokoto
        cd ./hitokoto
        curl  -H $HEAD https://api.mhuig.top/hitokoto -o hitokoto.json
        curl  -H $HEAD https://api.mhuig.top/hitokoto/w -o hitokoto.js
        cd ..
        mkdir ./unsplash
        cd ./unsplash
        curl  -H $HEAD https://api.mhuig.top/unsplash -o unsplash.jpg


    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./

    - name: Purge
      run: |
        curl https://purge.jsdelivr.net/gh/MHG-LAB/cron@gh-pages/bing/bing.jpg
        curl https://purge.jsdelivr.net/gh/MHG-LAB/cron@gh-pages/bing/1.jpg
        curl https://purge.jsdelivr.net/gh/MHG-LAB/cron@gh-pages/bing/2.jpg
        curl https://purge.jsdelivr.net/gh/MHG-LAB/cron@gh-pages/bing/3.jpg
        curl https://purge.jsdelivr.net/gh/MHG-LAB/cron@gh-pages/bing/4.jpg
        curl https://purge.jsdelivr.net/gh/MHG-LAB/cron@gh-pages/bing/5.jpg
        curl https://purge.jsdelivr.net/gh/MHG-LAB/cron@gh-pages/bing/6.jpg
        curl https://purge.jsdelivr.net/gh/MHG-LAB/cron@gh-pages/bing/7.jpg
        curl https://purge.jsdelivr.net/gh/MHG-LAB/cron@gh-pages/bing/bing.js
        curl https://purge.jsdelivr.net/gh/MHG-LAB/cron@gh-pages/bing/1.js
        curl https://purge.jsdelivr.net/gh/MHG-LAB/cron@gh-pages/bing/2.js
        curl https://purge.jsdelivr.net/gh/MHG-LAB/cron@gh-pages/bing/3.js
        curl https://purge.jsdelivr.net/gh/MHG-LAB/cron@gh-pages/bing/4.js
        curl https://purge.jsdelivr.net/gh/MHG-LAB/cron@gh-pages/bing/5.js
        curl https://purge.jsdelivr.net/gh/MHG-LAB/cron@gh-pages/bing/6.js
        curl https://purge.jsdelivr.net/gh/MHG-LAB/cron@gh-pages/bing/7.js
        curl https://purge.jsdelivr.net/gh/MHG-LAB/cron@gh-pages/bing/bing.json
        curl https://purge.jsdelivr.net/gh/MHG-LAB/cron@gh-pages/bing/1.json
        curl https://purge.jsdelivr.net/gh/MHG-LAB/cron@gh-pages/bing/2.json
        curl https://purge.jsdelivr.net/gh/MHG-LAB/cron@gh-pages/bing/3.json
        curl https://purge.jsdelivr.net/gh/MHG-LAB/cron@gh-pages/bing/4.json
        curl https://purge.jsdelivr.net/gh/MHG-LAB/cron@gh-pages/bing/5.json
        curl https://purge.jsdelivr.net/gh/MHG-LAB/cron@gh-pages/bing/6.json
        curl https://purge.jsdelivr.net/gh/MHG-LAB/cron@gh-pages/bing/7.json
        curl https://purge.jsdelivr.net/gh/MHG-LAB/cron@gh-pages/soul/soul.json
        curl https://purge.jsdelivr.net/gh/MHG-LAB/cron@gh-pages/soul/soul.js
        curl https://purge.jsdelivr.net/gh/MHG-LAB/cron@gh-pages/hitokoto/hitokoto.js
        curl https://purge.jsdelivr.net/gh/MHG-LAB/cron@gh-pages/hitokoto/hitokoto.js
        curl https://purge.jsdelivr.net/gh/MHG-LAB/cron@gh-pages/unsplash/unsplash.jpg


